### ISSUE TITLE
createRunnerProject does not work

### ISSUE THREAD

**Issue by kincsescsaba** [JetBrains/sbt-idea-plugin#10]
Hi, I added a createRunnerProject call to my build.sbt but the idea-runner module does not get generated.

Related part looks like this:

> lazy val macroPlugin = (project in file("plugin"))
>   .settings(commonSettings)
>   .settings(ideaSettings)
>   .settings(packagingSettings)
>   .settings(
>     name := "macroannotation-idea"
>   )
>   .enablePlugins(SbtIdeaPlugin)
> 
> lazy val ideaRunner: Project =
>   createRunnerProject(macroPlugin, "idea-runner")

**Comment by kincsescsaba** [comment]
UPDATE: it gets generated under root target, but running packagePlugin throws an error

java.util.NoSuchElementException: key not found: ProjectRef(file:/home/user/IdeaProjects/macroannotation_scala213/,idea-runner)
[error] 	at scala.collection.immutable.Map$Map1.apply(Map.scala:111)
[error] 	at org.jetbrains.sbtidea.tasks.packaging.StructureBuilder.walk$1(StructureBuilder.scala:30)
[error] 	at org.jetbrains.sbtidea.tasks.packaging.StructureBuilder.artifactMappings(StructureBuilder.scala:131)
[error] 	at org.jetbrains.sbtidea.Keys$.$anonfun$projectSettings$27(Keys.scala:348)
[error] 	at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)

**Comment by mutcianm** [comment]
Are you running `packagePlugin` task from the "macroPlugin" project?

**Comment by kincsescsaba** [comment]
No, and looks like that was the problem, now the jar is generated.
Thanks for looking into this.
