### ISSUE TITLE
Upgrade to use sbt 1.9.x

### ISSUE THREAD

**Issue by ScalaWilliam** [JetBrains/sbt-idea-plugin#122]
Hi, it would be great if this plugin could be upgraded to use SBT 1.9.x, as that enables publishing to Maven Central in a Maven consistent format. More details here: https://github.com/sbt/sbt/issues/3410

**Comment by vasilmkd** [comment]
Hi 👋🏻 

Just updating the sbt.version in `project/build.properties` and republishing is enough?

**Comment by ScalaWilliam** [comment]
Hi @vasilmkd I believe so - release notes are here -- https://github.com/sbt/sbt/releases/tag/v1.9.0 -- and don't seem to indicate major changes. 1.9.6 would be the latest in the series.

**Comment by vasilmkd** [comment]
I will do the update on Monday at work.

**Comment by vasilmkd** [comment]
https://repo1.maven.org/maven2/org/jetbrains/sbt-idea-plugin_2.12_1.0/

Published the new version 3.20.5, built with sbt 1.9.6.

Indeed, it seems there is more metadata with the new style of publishing.

Thanks again for the report.

**Comment by ScalaWilliam** [comment]
This worked end to end - thank you so much @vasilmkd !!
