### ISSUE TITLE
Companion object cannot be referenced in plugin.xml using its name

### ISSUE THREAD

**Issue by zhutmost** [JetBrains/sbt-idea-plugin#127]
I am writing a custom `FileType` for a custom language. According to the sample Java code in the tutorial by JetBrains, I use a companion object to store the INSTANCE object:
```scala
class VerilogFileType extends LanguageFileType(VerilogLanguage.INSTANCE) {
  ...... // other code
}

object VerilogFileType {
  val INSTANCE = new VerilogFileType
}
```
and I add it to the plugin.xml:
```xml
        <fileType
            name="SystemVerilog"
            implementationClass="some.package.VerilogFileType" // here!
            fieldName="INSTANCE"
            language="SystemVerilog"
            extensions="sv;svh"/>
```
However, scala will rename the companion object (add a dollar "$" after its name) during compiling.
So, the above code cannot work.
To solution is to correct the plugin.xml, like this:
```xml
<fileType
   ...
            implementationClass="some.package.VerilogFileType$" // here a $ added!
   ....
/>
```
Now we can successfully generate a correct plugin zip.

**Comment by zhutmost** [comment]
Although we can workaround the problem, the Intellij IDEA will report unnecessary warning messages. 
<img width="1157" alt="image" src="https://github.com/JetBrains/sbt-idea-plugin/assets/20497382/6cf438a0-90fb-43db-babf-756427031d34">
I think this can be fixed.

**Comment by unkarjedy** [comment]
We also observe this issue in Scala Plugin.
<img width="997" alt="image" src="https://github.com/JetBrains/sbt-idea-plugin/assets/3989292/b54c209b-0fb0-4b19-87fa-4111270df99e">

But it's not an issue with sbt-idea-plugin, it's an issue with IntelliJ DevKit plugin.
Could you please report it at https://youtrack.jetbrains.com/newIssue?project=IJPL&draftId=25-5362851
and set the subsystem DevKit?
