### ISSUE TITLE
External plugins not attached

### ISSUE THREAD

**Issue by mutcianm** [JetBrains/sbt-idea-plugin#5]
trying to update an internal plugin (just support some fields generated with scala macros) for 2019.1-beta.

have tried sbt-idea-plugin 2.1.3, 2.3.0, and 2.3.1. My only external dependency is the Scala plugin. This dependency doesn't work, because:

it is extracted into the plugins directory instead of the `externalPlugins` directory, meaning `ideaExternalPluginsJars` doesn't pick up any jars
the scala plugin is extracted into a Scala directory, even though it already has a top-level Scala directory in the zip - so there's nothing in `Scala/lib` for `ideaExternalPluginsJars` to find - it's in `Scala/Scala/lib`

@codingismy11to7

**Comment by codingismy11to7** [comment]
is this the proper place for issues instead of the jetbrains issue tracker?

**Comment by mutcianm** [comment]
Yes, we don't have a dedicated YouTrack project for sbt-idea-plugin.
