### ISSUE TITLE
`packageArtifact` task does not respect `patchPluginXml`

### ISSUE THREAD

**Issue by Baccata** [JetBrains/sbt-idea-plugin#76]
Using version `3.7.5` of the sbt-idea-plugin sbt plugin to develop an Intellij Plugin :

When inspecting the output of `packageArtifact`, the contained `plugin.xml` has not been patched as expected

**Comment by Baccata** [comment]
apparently I need to run `doPatchPluginXml` manually, **only after** the project has already been compiled, before packaging it ... 

This is extremely unintuitive 😞

**Comment by mutcianm** [comment]
Hi! Patching, by design, should happen automatically before packaging the artifact.
Could you please link your plugin repo for me to take a closer look, if it's not private?

**Comment by Baccata** [comment]
it's currently in PR and part of a larger codebase, but here you go : https://github.com/disneystreaming/weaver-test/pull/74

**Comment by Baccata** [comment]
Mmm it does seem to work as expected now. I wonder if sbt had some stale cache under the hood that lead to the behaviour I witnessed the other day

**Comment by mutcianm** [comment]
A message should be printed when you call `packageArtifact...` task if the patching has actually been performed.
`[info] Detected plugin xmls, patching: ...`

**Comment by Baccata** [comment]
Yup it does now. when I opened the ticket there was nothing in the message after `patching:` ... anyhow, I'm okay to close the ticket for now, if the problem re-occurs I'll try to minimise it.
