### ISSUE TITLE
Unable to upload the plugin to marketplace - uses incorrect Id

### ISSUE THREAD

**Issue by hmemcpy** [JetBrains/sbt-idea-plugin#78]
I tried using `sbt uploadPlugin` to publish [my plugin](https://plugins.jetbrains.com/plugin/13820-zio-for-intellij) to the marketplace, however it failed with:

```
Error:  Failed to upload plugin
Error:  (400) : For input string: "zio.intellij.zio-intellij"
```

Upon deeper inspection, and reading the documentation for the [`uploadPlugin` API](https://plugins.jetbrains.com/docs/marketplace/plugin-upload.html), it seems that the sbt-idea-plugin extracts the XML Id of the plugin, but passes it as the `pluginId` parameter, which should be the numeric id.

I believe the correct parameter should be `xmlId`.

I verified it with curl and it was indeed the case:

Before:
```
curl -i --header "Authorization: Bearer perm:..." -F pluginId=zio.intellij.zio-intellij -F file=@./target/zio-intellij-2020.2.1.2.zip https://plugins.jetbrains.com/plugin/uploadPlugin
HTTP/2 400
...
For input string: "zio.intellij.zio-intellij"%
```

With numeric Id:
```
curl -i --header "Authorization: Bearer perm:..." -F pluginId=13820 -F file=@./target/zio-intellij-2020.2.1.2.zip https://plugins.jetbrains.com/plugin/uploadPlugin
HTTP/2 201
...
The ZIO for IntelliJ plugin has been successfully uploaded% 
```

With `xmlId`:
```
curl -i --header "Authorization: Bearer perm:..." -F xmlId=zio.intellij.zio-intellij -F file=@./target/zio-intellij-2020.2.1.2.zip https://plugins.jetbrains.com/plugin/uploadPlugin
HTTP/2 201
...
The ZIO for IntelliJ plugin has been successfully uploaded% 
```

**Comment by timaliberdov** [comment]
+1 for `xmlId` parameter.

For example, Gradle plugin uses JetBrains Plugin Repository Rest Client which supports both pluginId and xmlId.

Links to source code for reference:

- [Uploading from Gradle plugin](https://github.com/JetBrains/gradle-intellij-plugin/blob/2df8c655597f02b1afa94acc328ca1e2165b9759/src/main/groovy/org/jetbrains/intellij/tasks/PublishTask.groovy#L129)
- [Uploader in the client](https://github.com/JetBrains/plugin-repository-rest-client/blob/3339250797d41d4c064509007410514d7f5a6f32/rest/src/main/kotlin/org/jetbrains/intellij/pluginRepository/internal/instances/PluginUploaderInstance.kt#L29)
- [HTTP Call definition in the client](https://github.com/JetBrains/plugin-repository-rest-client/blob/3339250797d41d4c064509007410514d7f5a6f32/rest/src/main/kotlin/org/jetbrains/intellij/pluginRepository/internal/api/PluginRepositoryService.kt#L25)
