### ISSUE TITLE
Old sources in 3.7.6

### ISSUE THREAD

**Issue by timaliberdov** [JetBrains/sbt-idea-plugin#80]
Seems like the last fix for plugin id didn't get to a released jar.

[bintray link](https://bintray.com/jetbrains/sbt-plugins/sbt-idea-plugin/3.7.6#files/org.jetbrains%2Fsbt-idea-plugin%2Fscala_2.12%2Fsbt_1.0%2F3.7.6%2Fsrcs)

![image](https://user-images.githubusercontent.com/8186312/95759981-238c2b00-0cb3-11eb-8161-b7633f748d9b.png)

Could you update it, please?

**Comment by mutcianm** [comment]
Oops, sorry, network malfunction.
Correct build published as 3.7.7

**Comment by timaliberdov** [comment]
Thank you!
